### ISSUE TITLE
[BUG] no term for Sex = "Other" in docs

### ISSUE THREAD

**Issue by surchs** [neurobagel/documentation#30]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

BIDS allows "Other" as a value for Sex. We're using SNOMED for "Male" and "Female". I want a term for "other"

### Current Behavior

Docs don't say anything. Snomed doesn't have a term for "Other". There is "Indeterminate Sex" (32570681000036106), but I find that difficult as a term. The definition is clearly more targeted towards describing observable findings in a clinical context. 

i.e. here are several synonymous terms in SNOMED:
```
32570681000036106 | Indeterminate sex (finding) |
  en   Indeterminate sex (finding)
  en   Indeterminate sex
  en   Outer genital organs are not visually male or female.
```

That's likely not what's meant by "Other" in 99% of datasets. 
I see two solutions:

- drop SNOMED as the ontology of choice for "Sex"
- drop "Sex" as the variable and move to "Gender" to clarify that we are encoding what the participant answers to the question. 
- use the above SNOMED term internally and use the label of "indeterminate" for now, until we find a better solution

**Comment by surchs** [comment]
@alyssadai since you did the work to align terms across the tools: 
- any repo that's better suited for this issue?
- do you have any thoughts on this?

**Comment by alyssadai** [comment]
I think this is probably the best repo for this issue.

Aha, I remember seeing that SNOMED term used in your query for the [one-off OpenNeuro annotation](https://github.com/neurobagel/project/issues/80#issuecomment-1515275716) for `"Other"` sex. Was wondering what that actually was.

Agree that the definition of `"Indeterminate sex"` doesn't sound right for our purposes. From my understanding we want an option to represent "not male and not female".

I don't think I have a great idea regarding this unfortunately, but here are my thoughts on your suggestions 

> drop SNOMED as the ontology of choice for "Sex"

I'would be in favour of this only if there is another ontology that includes `"Other sex"` or some other term representing "not exclusively male or female"...which _may_ be difficult to find.

> drop "Sex" as the variable and move to "Gender" to clarify that we are encoding what the participant answers to the question

I don't think this is a good idea, because 1) a question that asks about sex can't be assumed to be about gender (even if a participant is supplying the answer), especially if "male"/"female" are the primary options 2) I don't think we can guarantee that all values for sex across different datasets are obtained directly from the user, and not taken from medical intake forms/records (which further lowers the likelihood of it being about gender)

> use the above SNOMED term internally and use the label of "indeterminate" for now, until we find a better solution

Hrm, yeah. It's not ideal but may be a fair option for now. I wonder if this might also be a use case for a custom `"nb:Other"` term, lol.

Just to double check, "other" sex would also be distinct from "missing" (unknown) sex, right?
